sudo: required
language: node_js
node_js:
  - '5'
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] ; then
    ./node_modules/.bin/surge --project ./dist --domain nerdsofalltrad.es ;
  else
    echo "Deployment omitted." ;
  fi

